apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: argo-canary
  labels:
    app: argo-canary
  annotations:
    # Se usar NGINX Ingress
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  ingressClassName: nginx # Padr√£o para Ingress NGINX
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: argo-canary
            port:
              number: 90
