apiVersion: v1
kind: Service
metadata:
  name: argo-canary
  labels:
    app: argo-canary
spec:
  type: ClusterIP
  selector:
    app: argo-canary
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
      name: http
